### ISSUE TITLE
Ctrl - D is probably a better quit command than Ctrl -Q

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli-shell#23]
...and if you disagree, then you have to handle Ctrl-D more gracefully..

At the moment, you get:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/JohanSte/temp/azshell/env/lib/python2.7/site-packages/azclishell/__main__.py", line 71, in <module>
    main(sys.argv[1:])
  File "/Users/JohanSte/temp/azshell/env/lib/python2.7/site-packages/azclishell/__main__.py", line 67, in main
    shell_app.run()
  File "/Users/JohanSte/temp/azshell/env/lib/python2.7/site-packages/azclishell/app.py", line 529, in run
    document = self.cli.run(reset_current_buffer=True)
  File "/Users/JohanSte/temp/azshell/env/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 432, in run
    return self.return_value()
  File "/Users/JohanSte/temp/azshell/env/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 820, in return_value
    return self._return_value()
  File "/Users/JohanSte/temp/azshell/env/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 563, in eof_error
    raise EOFError()

**Comment by johanste** [comment]
And also, Ctrl-C gives you a similar call stack...

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-cli-shell/issues/12?

**Comment by troydai** [comment]
I prefer `:q!`
