### ISSUE TITLE
"no attribute 'get_command_table'" when launching az-shell

### ISSUE THREAD

**Issue by berndverst** [Azure/azure-cli-shell#88]
When running `az-shell` I receive the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/bverst/Library/Python/2.7/lib/python/site-packages/azclishell/__main__.py", line 15, in <module>
    import azclishell._dump_help
  File "/Users/bverst/Library/Python/2.7/lib/python/site-packages/azclishell/_dump_help.py", line 6, in <module>
    from azclishell._dump_commands import dump_command_table
  File "/Users/bverst/Library/Python/2.7/lib/python/site-packages/azclishell/_dump_commands.py", line 20, in <module>
    CMD_TABLE = APPLICATION.configuration.get_command_table()
AttributeError: 'NoneType' object has no attribute 'get_command_table'
```

I installed the CLI Shell via `pip install azure-cli-shell --user`. I even tried running `pip install --upgrade --ignore-installed azure-cli-shell --user`. Both installs succeed without any issue. The issue happens in both ZSH and BASH.

Invoking the CLI shell via `az-shell` yields the above error.

OS: macOS 10.12.4

```
echo $SHELL
/bin/zsh

$SHELL --version
zsh 5.2 (x86_64-apple-darwin16.0)

which python
/usr/local/bin/python

python --version
Python 2.7.13

pip --version
pip 9.0.1 from /Users/bverst/Library/Python/2.7/lib/python/site-packages (python 2.7)

pip freeze

adal==0.4.5
appdirs==1.4.3
applicationinsights==0.10.0
appnope==0.1.0
argcomplete==1.8.2
asn1crypto==0.22.0
astroid==1.4.9
azure==1.0.3
azure-batch==2.0.0
azure-cli==2.0.3
azure-cli-acr==2.0.1
azure-cli-acs==2.0.3
azure-cli-appservice==0.1.3
azure-cli-batch==2.0.1
azure-cli-cloud==2.0.1
azure-cli-component==2.0.1
azure-cli-configure==2.0.3
azure-cli-container==0.1.3
azure-cli-core==2.0.3
azure-cli-documentdb==0.1.3
azure-cli-feedback==2.0.1
azure-cli-find==0.0.2
azure-cli-iot==0.1.3
azure-cli-keyvault==2.0.1
azure-cli-lab==0.0.2
azure-cli-monitor==0.0.2
azure-cli-network==2.0.3
azure-cli-nspkg==2.0.0
azure-cli-profile==2.0.3
azure-cli-redis==0.2.0
azure-cli-resource==2.0.3
azure-cli-role==2.0.2
azure-cli-shell==0.2.0
azure-cli-sql==2.0.1
azure-cli-storage==2.0.3
azure-cli-vm==2.0.3
azure-common==1.1.5
azure-graphrbac==0.30.0rc6
azure-keyvault==0.1.0
azure-mgmt==0.20.2
azure-mgmt-authorization==0.30.0rc6
azure-mgmt-batch==3.0.0
azure-mgmt-common==0.20.0
azure-mgmt-compute==1.0.0rc1
azure-mgmt-containerregistry==0.2.0
azure-mgmt-dns==1.0.0
azure-mgmt-documentdb==0.1.1
azure-mgmt-iothub==0.2.1
azure-mgmt-keyvault==0.30.0
azure-mgmt-monitor==0.1.0
azure-mgmt-network==1.0.0rc1
azure-mgmt-nspkg==2.0.0
azure-mgmt-redis==1.0.0
azure-mgmt-resource==1.0.0rc1
azure-mgmt-sql==0.4.0
azure-mgmt-storage==1.0.0rc1
azure-mgmt-trafficmanager==0.30.0rc6
azure-mgmt-web==0.31.0
azure-monitor==0.2.0
azure-multiapi-storage==0.1.0
azure-nspkg==2.0.0
azure-servicebus==0.20.1
azure-servicemanagement-legacy==0.20.2
azure-storage==0.20.3
backports-abc==0.5
backports.functools-lru-cache==1.3
backports.shutil-get-terminal-size==1.0.0
bleach==2.0.0
certifi==2017.4.17
cffi==1.10.0
click==6.7
colorama==0.3.7
configparser==3.5.0
cryptography==1.8.1
decorator==4.0.11
Django==1.10.6
entrypoints==0.2.2
enum34==1.1.6
Flask==0.12
functools32==3.2.3.post2
futures==3.1.1
greenlet==0.4.12
gunicorn==19.7.1
haxor-news==0.4.1
html5lib==0.999999999
idna==2.5
ipaddress==1.0.18
ipykernel==4.6.0
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isodate==0.5.4
isort==4.2.5
itsdangerous==0.24
Jinja==1.2
Jinja2==2.9.6
jmespath==0.9.2
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
keyring==10.3.2
lazy-object-proxy==1.2.2
MarkupSafe==1.0
mccabe==0.6.1
mistune==0.7.4
msgpack-python==0.4.8
msrest==0.4.7
msrestazure==0.4.7
nbconvert==5.1.1
nbformat==4.3.0
ndg-httpsclient==0.4.2
neovim==0.1.13
notebook==5.0.0
oauthlib==2.0.2
packaging==16.8
pandocfilters==1.4.1
paramiko==2.1.2
pathlib2==2.2.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pyasn1==0.2.3
pycparser==2.17
Pygments==2.2.0
PyJWT==1.4.2
pylint==1.6.5
pyOpenSSL==16.2.0
pyparsing==2.2.0
python-dateutil==2.6.0
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.3.0
requests==2.13.0
requests-oauthlib==0.8.0
scandir==1.5
scp==0.10.2
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
sshtunnel==0.1.2
tabulate==0.7.7
terminado==0.6
testpath==0.3
tornado==4.4.3
traitlets==4.3.2
trollius==2.1
urllib3==1.16
wcwidth==0.1.7
webencodings==0.5
Werkzeug==0.12.1
Whoosh==2.7.4
widgetsnbextension==2.0.0
wrapt==1.10.10
xmltodict==0.10.2
```

**Comment by berndverst** [comment]
@johnpapa is experiencing the same issue as me

**Comment by kongou-ae** [comment]
Me too.

**Comment by lmazuel** [comment]
Saw it as comment in the blog post as well:
https://azure.microsoft.com/en-us/blog/welcome-to-azure-cli-shell/#comment-3261173254

**Comment by derekbekoe** [comment]
@oakeyc can you take a look?

**Comment by oakeyc** [comment]
PR #69 will address this
