### ISSUE TITLE
az-shell does not work "on my machine" Windows 10 Pro (1607) x64

### ISSUE THREAD

**Issue by noopman** [Azure/azure-cli-shell#89]
---
C:\Code>az --version
azure-cli (2.0.0)

acs (2.0.0)
appservice (0.1.1b5)
batch (0.1.1b4)
cloud (2.0.0)
component (2.0.0)
configure (2.0.0)
container (0.1.1b4)
core (2.0.0)
documentdb (0.1.1b2)
feedback (2.0.0)
iot (0.1.1b3)
keyvault (0.1.1b5)
network (2.0.0)
nspkg (2.0.0)
profile (2.0.0)
redis (0.1.1b3)
resource (2.0.0)
role (2.0.0)
shell (0.2.0)
sql (0.1.1b5)
storage (2.0.1)
vm (2.0.0)

Python (Windows) 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]

C:\Code>az-shell
Traceback (most recent call last):
  File "C:\Users\{username}\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\{username}\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\{username}\AppData\Roaming\Python\Python35\site-packages\azclishell\__main__.py", line 18, in <module>
    from azclishell.app import Shell
  File "C:\Users\{username}\AppData\Roaming\Python\Python35\site-packages\azclishell\app.py", line 38, in <module>
    from azure.cli.core._config import az_config, DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION'

**Comment by oakeyc** [comment]
You would need to update your CLI to 2.0.3 and shell to 0.2.2

**Comment by mayurid** [comment]
@noopman : Let us know if you have this working. If not just reactivate the issue or shoot us a mail at azfeedback@microsoft.com

**Comment by noopman** [comment]
There were multiple issues but now they are resolved. I had to set a custom path and I had to reinstall things. Issue is closed for me too, thanks!
